In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Machine Learning/data/global-data-on-sustainable-energy (1).csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

##Questions:
1. Identify the relationship between the Renewable Energy Share and GDP per capita over time for countries in different income categories.
2. Show the first 5 rows of data for countries with the greatest decline in Carbon Dioxide Emissions (metric tons per capita) between 2005 and 2015.
3. Can you identify countries that have effectively disengaged economic growth from carbon emissions?
4. Examine the influence of Financial Flows to Developing Countries (US $) on the Renewable-Electricity-Generating-Capacity-Per-Capita for nations with varying levels of GDP per capita.
5. can you generate a time-series line chart depicting the annual change in Carbon Dioxide Emissions (metric tons per capita) for the region with highest emmisions?

In [ ]:
df

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [ ]:
df.dtypes

Entity                                                               object
Year                                                                  int64
Access to electricity (% of population)                             float64
Access to clean fuels for cooking                                   float64
Renewable-electricity-generating-capacity-per-capita                float64
Financial flows to developing countries (US $)                      float64
Renewable energy share in the total final energy consumption (%)    float64
Electricity from fossil fuels (TWh)                                 float64
Electricity from nuclear (TWh)                                      float64
Electricity from renewables (TWh)                                   float64
Low-carbon electricity (% electricity)                              float64
Primary energy consumption per capita (kWh/person)                  float64
Energy intensity level of primary energy (MJ/$2017 PPP GDP)         float64
Value_co2_emissions_kt_by_country                                   float64
Renewables (% equivalent primary energy)                            float64
gdp_growth                                                          float64
gdp_per_capita                                                      float64
Density\n(P/Km2)                                                     object
Land Area(Km2)                                                      float64
Latitude                                                            float64
Longitude                                                           float64
dtype: object

In [ ]:
df.isna().sum()

Entity                                                                 0
Year                                                                   0
Access to electricity (% of population)                               10
Access to clean fuels for cooking                                    169
Renewable-electricity-generating-capacity-per-capita                 931
Financial flows to developing countries (US $)                      2089
Renewable energy share in the total final energy consumption (%)     194
Electricity from fossil fuels (TWh)                                   21
Electricity from nuclear (TWh)                                       126
Electricity from renewables (TWh)                                     21
Low-carbon electricity (% electricity)                                42
Primary energy consumption per capita (kWh/person)                     0
Energy intensity level of primary energy (MJ/$2017 PPP GDP)          207
Value_co2_emissions_kt_by_country                                    428
Renewables (% equivalent primary energy)                            2137
gdp_growth                                                           317
gdp_per_capita                                                       282
Density\n(P/Km2)                                                       1
Land Area(Km2)                                                         1
Latitude                                                               1
Longitude                                                              1
dtype: int64

In [ ]:
df.shape

(3649, 21)

##Question 1

In [ ]:
df['gdp_per_capita'].sort_values(ascending = False) #3,367 / 3 = 1,122.333333 or 1,123

1968    123514.1967
1967    119966.0349
1962    119932.2437
1965    118869.2999
1972    117197.4817
           ...
3602            NaN
3603            NaN
3604            NaN
3605            NaN
3606            NaN
Name: gdp_per_capita, Length: 3649, dtype: float64

In [ ]:
df.columns

Index(['Entity', 'Year', 'Access to electricity (% of population)',
       'Access to clean fuels for cooking',
       'Renewable-electricity-generating-capacity-per-capita',
       'Financial flows to developing countries (US $)',
       'Renewable energy share in the total final energy consumption (%)',
       'Electricity from fossil fuels (TWh)', 'Electricity from nuclear (TWh)',
       'Electricity from renewables (TWh)',
       'Low-carbon electricity (% electricity)',
       'Primary energy consumption per capita (kWh/person)',
       'Energy intensity level of primary energy (MJ/$2017 PPP GDP)',
       'Value_co2_emissions_kt_by_country',
       'Renewables (% equivalent primary energy)', 'gdp_growth',
       'gdp_per_capita', 'Density\n(P/Km2)', 'Land Area(Km2)', 'Latitude',
       'Longitude', 'gdpSorted', 'High GDP'],
      dtype='object')

In [ ]:
gdpSorted = df['gdp_per_capita'].sort_values(ascending = False)

In [ ]:
v = gdpSorted.iloc[1123]

In [ ]:
v

9547.852151

In [ ]:
df['gdp_per_capita'].sort_values(ascending = False).head(20)

1968    123514.1967
1967    119966.0349
1962    119932.2437
1965    118869.2999
1972    117197.4817
418     117098.4463
1974    116014.6025
1973    113218.7133
417     113023.1856
1966    112591.1162
416     111820.5815
1964    110777.9079
1971    109921.0314
1963    108987.6776
1961    107338.8652
419     107079.4798
407     106935.4863
415     106885.8785
1970    106826.7264
1969    105419.6085
Name: gdp_per_capita, dtype: float64

In [ ]:
df['gdpSorted'].head(20)

0            NaN
1            NaN
2     179.426579
3     190.683814
4     211.382074
5     242.031313
6     263.733602
7     359.693158
8     364.663542
9     437.268740
10    543.306526
11    591.190030
12    638.845852
13    624.315454
14    614.223342
15    556.007221
16    512.012778
17    516.679862
18    485.668419
19    494.179350
Name: gdpSorted, dtype: float64

In [ ]:
df['High GDP'] = df.iloc[:1123, 21]

In [ ]:
df['Mid GDP'] = df.iloc[1124:2246, 21]

In [ ]:
df['Low GDP'] = df.iloc[2247:3367, 21]

In [ ]:
k = 0
while ~(k==3367):
  if(df['gdp_per_capita']>9547.852151):

In [ ]:
df.head(10)

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude,gdpSorted,High GDP,Mid GDP,Low GDP
0,Afghanistan,2000,1.613591,6.20,9.22,20000.0,44.99,0.16,0.0,0.31,...,NaN,NaN,60,652230.0,33.93911,67.709953,NaN,NaN,NaN,NaN
1,Afghanistan,2001,4.074574,7.20,8.86,130000.0,45.60,0.09,0.0,0.50,...,NaN,NaN,60,652230.0,33.93911,67.709953,NaN,NaN,NaN,NaN
2,Afghanistan,2002,9.409158,8.20,8.47,3950000.0,37.83,0.13,0.0,0.56,...,NaN,179.426579,60,652230.0,33.93911,67.709953,179.426579,179.426579,NaN,NaN
3,Afghanistan,2003,14.738506,9.50,8.09,25970000.0,36.66,0.31,0.0,0.63,...,8.832278,190.683814,60,652230.0,33.93911,67.709953,190.683814,190.683814,NaN,NaN
4,Afghanistan,2004,20.064968,10.90,7.75,NaN,44.24,0.33,0.0,0.56,...,1.414118,211.382074,60,652230.0,33.93911,67.709953,211.382074,211.382074,NaN,NaN
5,Afghanistan,2005,25.390894,12.20,7.51,9830000.0,33.88,0.34,0.0,0.59,...,11.229715,242.031313,60,652230.0,33.93911,67.709953,242.031313,242.031313,NaN,NaN
6,Afghanistan,2006,30.718690,13.85,7.40,10620000.0,31.89,0.20,0.0,0.64,...,5.357403,263.733602,60,652230.0,33.93911,67.709953,263.733602,263.733602,NaN,NaN
7,Afghanistan,2007,36.051010,15.30,7.25,15750000.0,28.78,0.20,0.0,0.75,...,13.826320,359.693158,60,652230.0,33.93911,67.709953,359.693158,359.693158,NaN,NaN
8,Afghanistan,2008,42.400000,16.70,7.49,16170000.0,21.17,0.19,0.0,0.54,...,3.924984,364.663542,60,652230.0,33.93911,67.709953,364.663542,364.663542,NaN,NaN
9,Afghanistan,2009,46.740050,18.40,7.50,9960000.0,16.53,0.16,0.0,0.78,...,21.390528,437.268740,60,652230.0,33.93911,67.709953,437.268740,437.268740,NaN,NaN

In [ ]:
df.loc[:,('Renewable energy share in the total final energy consumption (%)','High GDP', 'Mid GDP', 'Low GDP')]

,Renewable energy share in the total final energy consumption (%),High GDP,Mid GDP,Low GDP
0,44.99,NaN,NaN,NaN
1,45.60,NaN,NaN,NaN
2,37.83,179.426579,NaN,NaN
3,36.66,190.683814,NaN,NaN
4,44.24,211.382074,NaN,NaN
...,...,...,...,...
3644,81.90,NaN,NaN,NaN
3645,82.46,NaN,NaN,NaN
3646,80.23,NaN,NaN,NaN
3647,81.50,NaN,NaN,NaN
3648,81.90,NaN,NaN,NaN

##Question 2

Show the first 5 rows of data for countries with the greatest decline in Carbon Dioxide Emissions (metric tons per capita) between 2005 and 2015.

In [ ]:
df

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [ ]:
df.columns

Index(['Entity', 'Year', 'Access to electricity (% of population)',
       'Access to clean fuels for cooking',
       'Renewable-electricity-generating-capacity-per-capita',
       'Financial flows to developing countries (US $)',
       'Renewable energy share in the total final energy consumption (%)',
       'Electricity from fossil fuels (TWh)', 'Electricity from nuclear (TWh)',
       'Electricity from renewables (TWh)',
       'Low-carbon electricity (% electricity)',
       'Primary energy consumption per capita (kWh/person)',
       'Energy intensity level of primary energy (MJ/$2017 PPP GDP)',
       'Value_co2_emissions_kt_by_country',
       'Renewables (% equivalent primary energy)', 'gdp_growth',
       'gdp_per_capita', 'Density\n(P/Km2)', 'Land Area(Km2)', 'Latitude',
       'Longitude'],
      dtype='object')

In [ ]:
df[(df['Year']>=2005) & (df['Year']<=2015)]

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
5,Afghanistan,2005,25.390894,12.20,7.51,9830000.0,33.88,0.34,0.0,0.59,...,252.06912,1.41,1549.999952,NaN,11.229715,242.031313,60,652230.0,33.939110,67.709953
6,Afghanistan,2006,30.718690,13.85,7.40,10620000.0,31.89,0.20,0.0,0.64,...,304.42090,1.50,1759.999990,NaN,5.357403,263.733602,60,652230.0,33.939110,67.709953
7,Afghanistan,2007,36.051010,15.30,7.25,15750000.0,28.78,0.20,0.0,0.75,...,354.27990,1.53,1769.999981,NaN,13.826320,359.693158,60,652230.0,33.939110,67.709953
8,Afghanistan,2008,42.400000,16.70,7.49,16170000.0,21.17,0.19,0.0,0.54,...,607.83350,1.94,3559.999943,NaN,3.924984,364.663542,60,652230.0,33.939110,67.709953
9,Afghanistan,2009,46.740050,18.40,7.50,9960000.0,16.53,0.16,0.0,0.78,...,975.04816,2.25,4880.000114,NaN,21.390528,437.268740,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3639,Zimbabwe,2011,36.900000,30.10,66.20,1080000.0,79.27,3.43,0.0,5.51,...,3860.78980,11.77,11409.999850,NaN,14.193913,1093.653409,38,390757.0,-19.015438,29.154857
3640,Zimbabwe,2012,44.000000,29.80,65.14,NaN,77.50,3.25,0.0,5.68,...,4106.94970,10.42,12010.000230,NaN,16.665429,1304.968011,38,390757.0,-19.015438,29.154857
3641,Zimbabwe,2013,40.498375,29.80,64.44,319000000.0,78.87,3.90,0.0,5.36,...,4085.33200,10.48,12279.999730,NaN,1.989493,1429.998461,38,390757.0,-19.015438,29.154857
3642,Zimbabwe,2014,32.300000,29.50,63.38,17830000.0,80.27,3.92,0.0,5.79,...,3940.88620,10.40,12079.999920,NaN,2.376929,1434.896277,38,390757.0,-19.015438,29.154857
3643,Zimbabwe,2015,33.700000,29.50,63.54,NaN,80.82,4.02,0.0,5.37,...,3860.92020,10.36,12430.000310,NaN,1.779873,1445.069702,38,390757.0,-19.015438,29.154857

In [ ]:
filtered_df = df[df['Year'].isin([2005, 2015])]

In [ ]:
filtered_df = filtered_df[['Entity', 'Year', 'Value_co2_emissions_kt_by_country']]

In [ ]:
agg_df = filtered_df.groupby(['Entity', 'Year'])['Value_co2_emissions_kt_by_country'].sum().unstack().reset_index()

In [ ]:
agg_df['Change_in_CO2_emissions_kt'] = agg_df[2015] - agg_df[2005]

In [ ]:
agg_df = agg_df.sort_values(by='Change_in_CO2_emissions_kt', ascending=True)

In [ ]:
agg_df['Entity'].head(5)

168     United States
167    United Kingdom
78              Italy
165           Ukraine
149             Spain
Name: Entity, dtype: object

##Question 3

Can you identify countries that have effectively disengaged economic growth from carbon emissions?

No, but  I can identidy coutnris that have effectivelengaged economic growth from carbn emissions

In [ ]:
df

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [ ]:
df.isna().sum()

Entity                                                                 0
Year                                                                   0
Access to electricity (% of population)                               10
Access to clean fuels for cooking                                    169
Renewable-electricity-generating-capacity-per-capita                 931
Financial flows to developing countries (US $)                      2089
Renewable energy share in the total final energy consumption (%)     194
Electricity from fossil fuels (TWh)                                   21
Electricity from nuclear (TWh)                                       126
Electricity from renewables (TWh)                                     21
Low-carbon electricity (% electricity)                                42
Primary energy consumption per capita (kWh/person)                     0
Energy intensity level of primary energy (MJ/$2017 PPP GDP)          207
Value_co2_emissions_kt_by_country                                    428
Renewables (% equivalent primary energy)                            2137
gdp_growth                                                           317
gdp_per_capita                                                       282
Density\n(P/Km2)                                                       1
Land Area(Km2)                                                         1
Latitude                                                               1
Longitude                                                              1
dtype: int64

In [ ]:
df.groupby('Value_co2_emissions_kt_by_country')['gdp_growth'].apply(lambda x: x.sort_values(ascending = False))

Value_co2_emissions_kt_by_country
1.000000e+01                       3416    9.756098
                                   3412    9.142894
                                   3405    7.983261
                                   3399    7.886174
                                   3408    7.515954
                                             ...
9.984570e+06                       727     7.766150
1.000667e+07                       728     7.425764
1.009601e+07                       731     6.947201
1.050293e+07                       732     6.749774
1.070722e+07                       733     5.949714
Name: gdp_growth, Length: 3221, dtype: float64